version: 2
jobs:
  build:
    docker:
      - image: perl:5.28
    steps:
      - checkout
      - run: sudo apt update && sudo apt install -y --no-install-recommends imagemagick
      - run: cpanm --installdeps -n .
      - run: prove -lr
