version: 2
jobs:
  build:
    docker:
      - image: perl:5.30
    steps:
      - checkout
      - run: apt update && apt install -y --no-install-recommends imagemagick
      - run: curl -fsSL --compressed https://git.io/cpm | perl - install -g -w 3
      - run: prove -lr
