version: 2
jobs:
  build:
    docker:
      - image: perl:5.30
    steps:
      - checkout
      - run: apt update && apt install -y --no-install-recommends imagemagick
      - run: cpanm --installdeps -n .
      - run: prove -lr
